language: node_js

install:
  - npm install

branches:
  only:
    - master
deploy:
  provider: heroku
  api_key:
    secure: "r88qX8pyRKyXXSlLGH8c1Xqzn6o46ZCCgrS1Hh6OnYMRqQZOfhYrPdn0LDNFFjN/AAsSgfFoqWO2c0lqRf+XqTXoBBgAjmRkc+Bfz5Gre3yk/lb5IP1FZD3E5uOjnrs2ILSrWR2G3F/pZvhtOJhw7zk1D/5ZHcLdyw4zGZaYXCmV0zSyXSxJayIvFPIcOXiXOGVuVJHEZFwzkvreK1p7kuchMCBm42b3jYROnhwwzJvmrgPATklr3A6kh8RmozVhGQgqGyo46p7Pg0ujJoY2FRbOmeipmZ6NggrUO8ZlIPSXXb5Pk5p6uXu9R586HAkgKIeX/xG1ONUz8nGTBVrX1uD0sOpH/ROgdIFkPzw3rv9UQkjw2piHTwMtq/rHoum317d1FK70XnU0rVWVPj9zQf9MQktGL+v4hwb7w86b1E0pOyfKhOlM6U8/GdLbQpxE32xDEOpjyPWiUQutt+VxPcZbedEBb3sG7Q5vTOsHOWjyRHoIq46g1GM9o7o3szcA1OQGmubu3rX506YbkLTRNxNLCtBycAXSVVHoR4uCN27paW2NBB8qGRU+owrSZk8xP3tARJB3Z+RtzJTF3g0dhbH1Vc3bYDLgjSLGLDNBR7SCJamrejzxKYIDGVqGRRr3tgUoKfhVBMxacFJCJnW54mqyRa+6FPTfDJIvivvgyzw="
    app: garden-journal-backend